### ISSUE TITLE
No LICENSE or COPYING file

### ISSUE THREAD

**Issue by mithro** [cr1901/libmodem#1]
What license is this code under?

**Comment by cr1901** [comment]
It was GPLv3, but I suspect that's incompatible with your use cases, so I will relicense if necessary.

**Comment by mithro** [comment]
BSD/MIT (the same as Migen/LiteX) or Apache 2.0 would probably be ideal.

lgplv2 or later would also work (but less preferred).

**Comment by cr1901** [comment]
I'll relicense under Apache 2.0 then. Is that okay?

**Comment by mithro** [comment]
Yes that would be fine I think.

**Comment by mithro** [comment]
Dual license as Apache 2.0 or LGPLv2 or later

**Comment by mithro** [comment]
Would be okay to...
