### ISSUE TITLE
No README file...

### ISSUE THREAD

**Issue by mithro** [cr1901/libmodem#2]
Ya need one :-P

Some info on what protocols are supported, what OS work and how to build / install would be good.

**Comment by cr1901** [comment]
I added a README.md with the relevant information, with the following caveats:

* Build system is `scons`, I plan to switch to `meson`.
* You ask how to install to final location? Well, currently, you don't :P.

**Comment by cr1901** [comment]
README.md file has been added. Currently I still don't support installing, but everything else you asked for has been accounted for. Thus I'm closing :).
