### ISSUE TITLE
Same libmodem form 1999?

### ISSUE THREAD

**Issue by pbrunnen** [cr1901/libmodem#3]
Hello cr1901,
  Sorry I'm not able to easily tell and there didn't appear to be a better way to contact you.  Is this a continuation of the libmodem project by Riccardo Facchetti or does it just happen to have the same name?

Thank you.

**Comment by cr1901** [comment]
It just happens to have the same name, I'm afraid. I didn't know there was another libmodem project :(.

**Comment by pbrunnen** [comment]
Ah, Ok.  I had hoped that it might have been picked up.  Similar purpose also...
No worries.  Cheers!
